# Generated by Django 3.2.7 on 2021-09-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inicioSesion',
            fields=[
                ('idSesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=30)),
                ('hora', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimiento', models.CharField(max_length=30)),
                ('cantidadProducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
                ('hora', models.CharField(max_length=30)),
                ('valorTotal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30)),
                ('stockActual', models.CharField(max_length=30)),
                ('stockMinimo', models.CharField(max_length=30)),
                ('valorUnitario', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('idTienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('tienda', models.CharField(max_length=30)),
            ],
        ),
    ]
